### PR TITLE
Random stuff

### PR DESCRIPTION
**Pull request by lindakung**
@seemaullal @smuenzinger @tmoreton 
i found an interface i liked and attempted to replicate. i fixed the navbar and stuff but then i realized some things (the toggle menu and our fullstack logo) got lost in the changes. it's a nicer interface now if i do say so myself. it's very simple so I was thinking we can add a giant sandwich photo in the home page. make sure to gulp build.

### CODE REVIEW

**Comment by seemaullal** [comment]
@lindakung this looks great! Thanks for making our site suddenly look significantly better. This update seems to have affected some button functionality (for example, adding a sandwich from the menu no longer works for me). Also, I think the tray no longer moves as you scroll the page but I am not completely sure since I don't have enough data to really test this. These things can be fixed though and I think this is still ready to merge. :shipit:

**Comment by seemaullal** [comment]
In response to my previous comment- adding sandwiches does work, but it looks like you can't scroll down (my scroll bar is missing completely) so it looks like nothing is added. I think it's still fine to merge and we can try to make the tray function like it used to

**Comment by lindakung** [comment]
@seemaullal thanks for the input! i haven't encountered the scrollbar issue yet and didn't really look at the tray but i'll merge?

**Comment by seemaullal** [comment]
Yeah go ahead and merge @lindakung

**Pull request merged**
